# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Shane Kyi Hla Win, PhD
description: >- # this means to ignore newlines until "baseurl:"
  Information about Shane and what he is up to.
baseurl: "" # the subpath of the site
url: "https://shanekhw.github.io" # the base hostname & protocol for the site
og_image: /assets/img/IMG_8846.jpg
google_analytics: "GTM-MLX6C4M"

header:
  pages:
    - name: Home
      slug: /
    - name: Education
    - name: Positions
    - name: Projects
    - name: Publications
    - name: Tutorials

footer:
  show_powered_by: false
  contact:
    - name: Email
      value: shane@sutd.edu.sg
      link: mailto:shane@sutd.edu.sg

  follow:
    - name: Twitter
      link: https://twitter.com/shanese7en
      username: "@shanese7en"
    - name: LinkedIn
      link: www.linkedin.com/in/shanekhw
    - name: GitHub
      link: http://github.com/shanekhw

collections:
  tutorials: 
    output: true

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed
  

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
